### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by op3** [uga-uga/Horst#5]
Currently, horst will do all the calculations first and only write the results to disk at the very end. Consequently, the calculated spectra are needlessly clogging the memory. Especially for large Monte-Carlo simulations involving thousands of spectra, this can easily result in dozens of GB of memory being used.

Flushing spectra to disk immediately after calculation would considerably lessen the memory footprint of horst by up to a few orders of magnitude.

**Comment by u-eff-gee** [comment]
Between d92572b9bc5386c17ef572b8fa309b36fc5daaec and 61c2a41a0deb4b19d780d8a923a2d246aaabe63c, strongly reduced dependence of memory usage on the number of MC iterations. This was accomplished by addressing the issue above and initializing the ROOT TF1 fit function only a fixed number of times (ROOT seems to keep the fit functions in memory although they go out of scope in the program).
